### ISSUE TITLE
assembly.xml should be in the project root, not in resources

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-tool#1]
Using latest build of `bq` on Mac to create an app:
```
bq> new app
  > Artifact name ([group:]name[:version]): aa
  < Generating new Maven project aa ...
  < done.
```
The resulting app contains `assembly.xml` file in `src/main/resources/`, so it is included in the app `.jar` file after the build. I suggest to place it at the root of the project instead (i.e. in the same folder with `pom.xml`).

**Comment by stariy95** [comment]
done
